aws:
  region: "us-east-1"

plugins:
  - name: "eb"
    environments:
      -
        "name" : "my_eb_env"
        "route53":
          "switchable_dns" : "my.name.com"
          "zoneid" : "12345"
        charts:
          -
            "librato_space" : 1111
            "chart_type" : "bignumber"
          -
            "librato_space" : 2222
            "chart_type" : "line"
            "deploy_feed" : "deployments"

  - name: "ecs"
    clusters:
      -
        "name" : "my_ecs_cluster"
        "charts":
        -
          "librato_space" : 12345
          "chart_type" : "bignumber"
        -
          "librato_space" : 7890
          "chart_type" : "line"
          "deploy_feed" : "deployments"
