aws:
  region: "us-east-1"

plugins:
  - name: "eb"
    environments:
      -
        "name" : "my_eb_env_1"
        "librato_space" : 1111
      -
        "name" : "my_eb_env_2"
        "librato_space" : 1111

  - name: "ecs"
    clusters:
      -
        "name" : "my_ecs_cluster_1"
        "librato_space" : 1234

